### ISSUE TITLE
color scheme changing at start

### ISSUE THREAD

**Issue by ml3515582** [mallowigi/material-theme-jetbrains-docs#209]
In version 1.3.2,this problem is still exist

**Comment by mallowigi** [comment]
Can you tell me the exact steps how to reproduce? Which IDE? plugin version?

**Comment by ml3515582** [comment]
plugin version:
![image](https://user-images.githubusercontent.com/4177989/33006731-77d48638-ce06-11e7-8e10-8fb0e812b498.png)
IDE: andnroid studio 3.0  and intellij IDEA version 2017.2.6  all exist
step: i only changed Preference->Editor->Colors & Fonts -> Scheme
![image](https://user-images.githubusercontent.com/4177989/33006882-106f82ee-ce07-11e7-980a-b15900e8aebf.png)
then i close the idea and start it.
the Scheme has bean changed to Darcula.

**Comment by ml3515582** [comment]
i used color scheme is from https://github.com/jkaving/intellij-colors-solarized

**Comment by ml3515582** [comment]
the solarized color is beautiful ，you can integration it.😁
