### ISSUE TITLE
Material Theme UI incompatible with IntelliJ 2018.2

### ISSUE THREAD

**Issue by JayJayM** [mallowigi/material-theme-jetbrains-docs#217]
Hi, 

I just upgraded IntelliJ to 2018.2 and the Material Theme UI plugin is incompatible with this version 😢  

Any chance we could make it work? Anything I should do on my end?

Thank you ! 🙏

**Comment by mallowigi** [comment]
Are you sure you’re using the material theme ui and not a residue of the old material theme eap?

**Comment by JayJayM** [comment]
@mallowigi 
I received an update of `Material Theme UI` this morning and it now works on IntelliJ 2018.2.

I'll close this issue. 
Thank you very much for your answer.
