### ISSUE TITLE
font chaos

### ISSUE THREAD

**Issue by menedas** [mallowigi/material-theme-jetbrains-docs#221]
Hi, after last update most of the fonts in phpstorm arent readable anymore. Now i need to disable material plugin to be able to work with phpstorm. How can I use the plugin again?

On Windows 10 and PhpStorm 2018.2.5

**Comment by mallowigi** [comment]
I've disabled the font support in 2.9.6. Theoretically it should return to the default fonts.

Which version are you on ?

**Comment by menedas** [comment]
2.9.6

**Comment by mallowigi** [comment]
I know but try.

**Comment by mallowigi** [comment]
never mind. I see it happening on my computer. Will fix it.

**Comment by mallowigi** [comment]
never mind. Here's what you need to do:

1. First go to "Appearance > OVerride custom fonts" and select another font, like Arial for instance
2. Open the registry by typing `Ctrl+Shift+A` and type "Registry"
3. Check if the "bigger.fonts.in.project.view" is checked. Uncheck it.
4. Restart

**Comment by menedas** [comment]
That fixed it 👍
Thank you :)
