### ISSUE TITLE
Option to disable material theme

### ISSUE THREAD

**Issue by Davoleo** [mallowigi/material-theme-jetbrains-docs#223]
I would like to know if a disable option was planned.

Because sometimes I need to disable the plugin temporarily to try out some things, and it would be awesome if didn't have to uninstall it everytime :thinking:

**Comment by mallowigi** [comment]
there's already an option for that

**Comment by Davoleo** [comment]
could you tell me where is it located?

**Comment by mallowigi** [comment]
Look in the documentation
