### ISSUE TITLE
Material Theme don't work in WebStorm 2019.3

### ISSUE THREAD

**Issue by maxpavlov** [mallowigi/material-theme-jetbrains-docs#248]
Hey. I realize this is probably not a bug tracker for Material Theme plugin, but as WebStorm 2019.3 came out yesterday, the Material theme doesn't work as it is reported to be incompatible. Perhaps you could take a look and release another, compatible version if the fixes required are minor. Thanks.

**Comment by mallowigi** [comment]
Please update to the latest version
