### ISSUE TITLE
Quarkus Theme Request

### ISSUE THREAD

**Issue by VMGlobantGNBSudameris** [mallowigi/material-theme-jetbrains-docs#249]
Hello guys... with fear of misplacing this request/suggestion in the wrong place... Any chance of someone might like to develop a Quakus theme for IntelliJ? It is a beautiful and pleasant them to work with.

![image](https://user-images.githubusercontent.com/55590914/69873722-16c33c00-1287-11ea-9200-5157dade5279.png)

Thanks!

**Comment by mallowigi** [comment]
You can try to do so using the custom theme feature. You can even export your work once you’re done.
