### ISSUE TITLE
Directory index is already disposed

### ISSUE THREAD

**Issue by Aircodes-Adam** [mallowigi/material-theme-jetbrains-docs#250]
Hi! Don't know where to report or even should I.
I'm facing this error (just popping, but not interfere me).
PyCharm Pro 2019.2.4 with 4.5.2 version of Material Theme UI

Additional plugins installed (all latest version) except material theme ui:

- https://plugins.jetbrains.com/plugin/9525--env-files-support/
- https://plugins.jetbrains.com/plugin/7495--ignore/
- https://plugins.jetbrains.com/plugin/9707-ansi-highlighter/
- https://plugins.jetbrains.com/plugin/4230-bashsupport/
- https://plugins.jetbrains.com/plugin/10037-csv-plugin/
- https://plugins.jetbrains.com/plugin/12174-datalore/
- https://plugins.jetbrains.com/plugin/10233-discord-integration/
- https://plugins.jetbrains.com/plugin/11563-flake8-support/
- https://plugins.jetbrains.com/plugin/9746-ideolog/
- https://plugins.jetbrains.com/plugin/6098-nodejs/
- https://plugins.jetbrains.com/plugin/8575-nyan-progress-bar/
- https://plugins.jetbrains.com/plugin/7094-pug-ex-jade-/
- https://plugins.jetbrains.com/plugin/7973-sonarlint/
- https://plugins.jetbrains.com/plugin/9442-vue-js/

Error log: https://pastebin.com/Zy9yFFaq

Thank you for attention! :)

**Comment by mallowigi** [comment]
Your log trace is pointing to the discord plugin. In any case I can’t reproduce this but this doesn’t look like something that would hinder your work .
